### ISSUE TITLE
Release an Arduino UNO version

### ISSUE THREAD

**Issue by tomxposed** [PK-420/iBus2USB#1]
Hi Patrick,
It will be very useful if you convert it to an Arduino UNO version or maybe you can comment down here for what changes should be made in order to convert it to the UNO version.

**Comment by PK-420** [comment]
Hello Tom,

Unfortunately, the only Arduino Joystick Library that I found does not support non-32u4 based Arduino devices (e.g. Arduino UNO, Arduino MEGA, etc.). The major change for reading iBus data on your Serial RX pin will be to replace "Serial1." with "Serial." where needed, I think that's already commented in the code.

Hope this helps
